CREATE TABLE request (
  requestID                     INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (requestID),
  requestDate                   TIMESTAMP,
  createdByID                   INT,
  FOREIGN KEY (createdByID) REFERENCES user (userId),
  caseNumber                    INT,
  caseTypeID                    INT,
  FOREIGN KEY (caseTypeID) REFERENCES casetype (caseTypeID),
  suspectUserName               VARCHAR(256),
  suspectLastName               VARCHAR(256),
  suspectFirstName              VARCHAR(256),
  suspectMiddleName             VARCHAR(256),
  suspectRegisteredEmailAddress VARCHAR(256),
  suspectRegisteredPhoneNumber  VARCHAR(256),
  requestSearchFromDate         DATE,
  requestSearchThroughDate      DATE,
  suspectContactInformation     BIT(1),
  suspectMiniFeed               BIT(1),
  suspectStatusHistory          BIT(1),
  suspectShares                 BIT(1),
  suspectNotes                  BIT(1),
  suspectWallPostings           BIT(1),
  suspectFriendList             BIT(1),
  suspectGroupList              BIT(1),
  suspectVideoList              BIT(1),
  suspectPastEvents             BIT(1),
  suspectFutureEvents           BIT(1),
  suspectPhotos                 BIT(1),
  suspectPrivateMessages        BIT(1),
  suspectGroupInfo              BIT(1),
  suspectIPLogs                 BIT(1),
  filterStartTime               TIME,
  filterEndTime                 TIME,
  filterCommunicantsUserName    VARCHAR(256),
  filterKeywords                VARCHAR(256),
  filterKeywordsCategory        INT,
  filterLocation                VARCHAR(256),
  requestStateID                INT,
  FOREIGN KEY (requestStateID) REFERENCES requeststate (requestStateID)
);